name: 'Jest Coverage Diff'
description: 'A github action to comment jest coverage diff on a PR'
author: 'Tal Kleiner'
inputs:
  accessToken:
    description: 'access token required to comment on a pr'
    default: ${{ github.token }}
  newCoveragePath:
    description: 'path to the new coverage directory (searches recursively for coverage-summary.json files)'
    required: true
  oldCoveragePath:
    description: 'path to the old/baseline coverage directory (searches recursively for coverage-summary.json files)'
    required: true
  delta:
    description: 'Difference between the old and final test coverage'
    default: 100
  total_delta:
    description: 'Difference between the old and final test coverage at the total level'
    default: null
  useSameComment:
    description: 'While commenting on the PR update the exisiting comment'
    default: false
branding:
  color: red
  icon: git-pull-request
runs:
  using: 'node12'
  main: 'dist/index.js'
